### ISSUE TITLE
BasicFileChooser fails to build on Java 9

### ISSUE THREAD

**Issue by FauxFaux** [Starlink/starjava#18]
In Java 9, many `awt` internal APIs have been moved or made private. `BasicFileChooser` uses these:

https://github.com/Starlink/starjava/blob/d0827466450e1d2ae15763bb451ea4557c10bc8f/util/src/main/uk/ac/starlink/util/gui/BasicFileChooser.java#L49

`BasicFileChooser` looks like a bit of a hack to make Java 1.4 work slightly better. Given it's unlikely that anyone is running Java 1.4 anymore (or 1.5, or 1.6, for that matter), perhaps it can just be removed? Or maybe someone on Windows can check if it's still doing anything, or if it's actively harmful.

```
build:
    [mkdir] Created dir: /build/starjava-util-1.0+2017.03.17/build/classes
    [javac] Compiling 95 source files to /build/starjava-util-1.0+2017.03.17/build/classes
    [javac] /build/starjava-util-1.0+2017.03.17/src/main/uk/ac/starlink/util/gui/BasicFileChooser.java:49: error: package sun.awt.shell is not visible
    [javac] import sun.awt.shell.ShellFolder;
    [javac]               ^
    [javac]   (package sun.awt.shell is declared in module java.desktop, which does not export it)
```

Cheers.

**Comment by olebole** [comment]
This was also reported as Debian [#873253](https://bugs.debian.org/873253). `ShellFolder` is however used only on Windows, [to follow a `.lnk` shortcut file to its origin](https://github.com/Starlink/starjava/blob/d0827466450e1d2ae15763bb451ea4557c10bc8f/util/src/main/uk/ac/starlink/util/gui/BasicFileChooser.java#L140-L141).
For the Debian package, I will just remove these lines. [Stackoverflow](https://stackoverflow.com/questions/309495/windows-shortcut-lnk-parser-in-java) has a possible implementation for Windows shortcuts.

**Comment by mbtaylor** [comment]
I will note that there is no dependency on this class from TOPCAT/STILTS, so I don't have any objection to removing this class or any other workaround to avoid the build problem.  The dependencies appear to be in SPLAT and (the moribund) SoG, so @mmpcn or @pwdraper should comment.

**Comment by mbtaylor** [comment]
I have finally got round to addressing this by removing references to the offending class (238392d).

This may have a negative effect on SPLAT, since the workaround for windows shortcut files in the file browser will no longer be effective.  However, I wouldn't be surprised if changes in the combination of OS and java platform over the last 15 years mean that this workaround is no longer necessary or effective.

Probably SPLAT should stop using the BasicFileChooser class in favour of JFileChooser now; @mmpcn and possibly @pwdraper might want to look at that.  If they do make that change, BasicFileChooser can be deleted altogether.
