### ISSUE TITLE
starlink and nom.tam.fits library

### ISSUE THREAD

**Issue by cwang2016** [Starlink/starjava#19]
For our service implementation, we are using both starlink library (stil.jar) and nom.tam.fits library to handle  FITS image, FITS table and votable. 

We just did some upgrade on nom.tam.fits library to the latest release, nom-tab-fits-1.15.2,
 (https://github.com/nom-tam-fits/nom-tam-fits/releases), and then run into some running crash which the service tried to get the table content from a votable or fits table. That crash occurred at the lines like 
                   ....
            StarTableFactory stFactory = new StarTableFactory();
            TableSequence tseq = stFactory.makeStarTables(voTableFile, null);
                   ... 
and got a Throwable exception like,  
      java.lang.NouchMethodError: nom.tam.fits.HeaderCard<init>(Ljava/lang/String;)V

This is what we found, 
- HeaderCard constructor like "public HeaderCard(String)" doesn't exist  in current nom.tam.fits release. 
- At the runtime, our service looks for HeaderCard class from the nom.tab.fits library, and that may result in  some conflict with stil.jar which also accesses nom.tam.fits, but that is not in sync with current nom.tam.fits release. 

Here is the question, 
- what is the nom.tam.fits release that current starlink library (stil.jar) includes? 
- Do you plan to apply the latest nom.tam.fits release into your future release? 
 
Thanks.

**Comment by mbtaylor** [comment]
Cindy,

STIL uses a slightly forked version of an ancient nom.tam.fits release, v0.93.  There are known issues, like the one you've come across, when using STIL with more recent versions of nom.tam.fits.  I plan to do something about this at some point, but not in the immediate future.

However, the Debian Astro package (https://blends.debian.org/astro/) contains a recent version of nom.tam.fits and versions of the libraries that go to make up STIL that have been patched to work with it.  I consider this somewhat less well tested than the official distribution, since I haven't gone through the effects of using the updated nom.tam.fits in fine detail (this is why I'm reluctant to upgrade nom.tam.fits in the official STIL), but I'm not aware of any known issues; probably it will be fine for any given usege.

So the best thing might be to acquire your STIL library, along with a matching nom.tam.fits, from debian.  It doesn't contain a monolithic stil.jar file, but all the dependencies you will need are available as dependencies of the starlink-ttools-java package:

    % apt-cache depends starlink-ttools-java
    starlink-ttools-java
      Depends: adql-java
      Depends: eag-healpix-java
      Depends: jel-java
      Depends: libandroid-json-org-java
      Depends: libcds-moc-java
      Depends: libcommons-io-java
      Depends: libfits-java
      Depends: libitext-java
      Depends: libjide-oss-java
      Depends: libjlatexmath-java
      Depends: libjlibeps-java
      Depends: libjsamp-java
      Depends: skyview-java
      Depends: starlink-fits-java
      Depends: starlink-pal-java
      Depends: starlink-registry-java
      Depends: starlink-table-java
      Depends: starlink-task-java
      Depends: starlink-util-java
      Depends: starlink-vo-java
      Depends: starlink-votable-java

so it should be possible to pull the required jar files out from a Debian distribution.  I'm not very knowledgeable about Debian packaging, but the person who did all the hard work for this is Ole Streicher (@olebole).  If you have questions on the details I suggest you append them to this issue and I expect Ole will be able to advise.

Note not all the packages in the dependency list above are required for STIL (though it's probably harmless to include them all).  Ole, would it make sense to define a STIL container package for people who just want (either within a Debian context or, as in this case, externally) to have the STIL I/O library but don't need STILTS or TOPCAT?  That would mirror the way I do my distribution.  However, I don't have strong feelings about whether Debian does it like that.

**Comment by olebole** [comment]
@mbtaylor One can just install the package [starlink-table-java](https://packages.debian.org/buster/starlink-table-java), since this automatically installs all dependencies.

For the FITS problem, our [libfits-java](https://packages.debian.org/buster/libfits-java) package still needs an update to 1.15.2 (which is the reason why I couldn't update TOPCAT & Co. in the moment).

Please note that problems with the Debian version should be reported to Debian (with `reportbug`), since they may be a result of the changes that I did to make everything Debian compliant. This especially includes the patches to use the current nom.tam.fits library:

 * [`fits/`](https://anonscm.debian.org/cgit/debian-astro/packages/starjava-fits.git/tree/debian/patches/Use-latest-nom.tam.fits-API.patch) (starjava-fits package in Debian)
 * [`votable/`](https://anonscm.debian.org/cgit/debian-astro/packages/starjava-votable.git/tree/debian/patches/Use-latest-nom.tam.fits-API.patch) (starjava-votable package in Debian)
 * [`datanode/`](https://anonscm.debian.org/cgit/debian-astro/packages/starjava-datanode.git/tree/debian/patches/Use-latest-nom.tam.fits-API.patch)  (starjava-datanode package in Debian)

(please note this may be not complete; I just quickly grepped through my patches, and it also covers only starjava subdirs that are requires for TOPCAT).

**Comment by mbtaylor** [comment]
Thanks @olebole, it looks like starlink-table-java does the trick for STIL dependencies.

@cwang2016, unless Ole says different, I'd guess there's a good chance that the existing patched Debian starlink-table-java classes will work with the vanilla 1.15.2 nom.tam.fits, if you don't want to wait for the Debian version.

**Comment by robyww** [comment]
@olebole have you published it back to mavin or do you have a github repository. We want to do builds outside the context Debian.

**Comment by olebole** [comment]
I maintain these patches only within the context of Debian (to create Debian packages). You may also want to check my other patches of the starjava packages, depending on your needs.

**Comment by cwang2016** [comment]
@olebole,  just wondering if there is package in Debian Astro package  that supports the classes like those in stil.jar  prefixed by 'uk/ac/bristol/star/cdf' ?
 
Thanks.

**Comment by mbtaylor** [comment]
@cwang2016, if you have it already that's fine, but the CDF reader classes are also distributed in a separate standalone package, JCDF, which you can find at http://www.star.bristol.ac.uk/~mbt/jcdf/.  In principle JCDF has a separate release schedule so might be more up to date than the STIL versions.  In practice though there is usually no difference.

If you're using those classes (for firefly?) I'd be interested to hear, and if you don't object to add that to the (short) list of known users on the JCDF web page.

**Comment by cwang2016** [comment]
@mbtaylor Thanks for the info. I got the jcdf package from Debian Astro package, and are collecting the relevant packages associated with those classes included in stil.jar.

@olebole,  does  libfits-java (1.15.2-1) from Debian Astro Packages match to nom-tam-fits-1.15.2?

**Comment by olebole** [comment]
@cwang2016 Upstream version is the one without the `-1`, so 1.10.0. I however yesterday uploaded 1.15.2 to unstable. What do you want to do, btw?

**Comment by timj** [comment]
@mbtaylor how much work do you think it is it to update starjava to use the new fits reader library?

FYI the LSST ticket is at https://jira.lsstcorp.org/browse/DM-11883

**Comment by mbtaylor** [comment]
Hi @timj .  The changes required to get the thing to build are pretty minor, less than a day's work.  In fact as per the comments above, @olebole  has already done it for debian-astro.

What's preventing me from just going ahead and doing it in the starlink/starjava master is the possibility that it might break something.  The nom.tam.fits version in starjava was forked from about v0.96? in 2003, and a few patches have been applied locally since then.  It's quite possible that there's nothing to worry about, but FITS I/O is pretty fundamental to STIL/STILTS/TOPCAT operation and I'm conservative about these things.  Before updating to a more recent version I would at least like to take a close look at all the source code changes between the old and current versions and run tests on FITS files I have lying around to check that everything looks OK.  But in fact I might instead try to cut loose of nom.tam.fits altogether for the important bits of STIL so I don't need to worry about upstream version changes now or in the future, since I actually only use small parts of the implementation (basically header parsing), having rewritten most of the bulk data access as custom code a long time ago.  Either way, I'd want a few days for it.

As you can see from the comments above, this is work-around-able for firefly by going via debian-astro on the assumption that the new nom.tam.fits does not cause unexpected problems.  But if LSST considers this a significant issue, I'd consider bumping the thing a few rungs up my to-do list.

**Comment by mbtaylor** [comment]
PS looking at the LSST ticket you mention: the jar files that are not found in astro-debian (ndx, gbin, rayreg, mirage) are pretty special-interest; STIL will work without them, and firefly is unlikely to need this functionality.  So you could just get away with the jar files you can find in astro-debian.

**Comment by olebole** [comment]
@mbtaylor
>  I might instead try to cut loose of nom.tam.fits altogether

I am a bit worried with such a decision: Having private libraries somehow isolates the development, which is not always a good idea for the community as a whole. The [issue](https://github.com/nom-tam-fits/nom-tam-fits/issues/113) with fitsPlus shows that quite clearly: Topcat introduced an (in the meantime) standard conform implementation to include some table metadata in a FITS file, but since the required changes were implemented in an internal fork of nom.tam.fits, no-one else could handle these files (the metadata would have been destroyed when processed by older nom.tam.fits versions, even if the user did not touch them).
I would prefer much to use public libs instead of writing own stuff. Especially nom.tam.fits seems to be quite conservative, so the danger of incompatible changes should be low.

But that are just my 2¢.

**Comment by robyww** [comment]
@mbtaylor and @olebole thanks for all the help. I am glad we (https://github.com/Caltech-IPAC/firefly), found a way to go forward (https://github.com/Caltech-IPAC/firefly/pull/472).  I do think having STIL being about to work in the same CLASSPATH with the most recent `nom.tam.fits` is worth the effort. I am sure we are not the only ones who would like to use both. Since they put https://github.com/nom-tam-fits/nom-tam-fits on github there has been a new development push with it. There will probably be others wanting to upgrade.

**Comment by mbtaylor** [comment]
@cwang2016, @robyww, @timj: I have done some work on this.  I've just made a new release, STIL v3.2-3, which is still bundled with the ancient version of nom.tam.fits, but ought now to run correctly (and build if you like) with nom.tam.fits v1.15.2, and hopefully future versions, as well.  The easiest way to use it is probably to grab the [stil_jars.zip](http://www.star.bristol.ac.uk/~mbt/stil/stil_jars.zip) file, unzip it to get the constituent jars and throw away the `tamfits.jar` file replacing it with your own.  But if you were doing something else before I expect that will work too.

Hopefully this will make your use of these classes smoother.  Let me know if you encounter any issues.
