### ISSUE TITLE
splat dipso saved sdf fit has an unknown type

### ISSUE THREAD

**Issue by paulkerry1** [Starlink/starjava#62]
Hi

When using splat to load output from a dipso "write" elf fit as sdf, splat fails to open the sdf with...
uk.ac.starlink.splat.util.SplatException: Spectrum '/tmp/pk.sdf' has an unknown type, format or name syntax(guessed: NDF )

It looks like it's just this method of sdf created file that fails as other sdf files I've tried open in splat. If I use convert and do a ndf2fits on the file, the resulting fits file will load in splat just fine. kappa-linplot on the sdf works fine too.

I've git cloned the starjava repo today into a clean directory and built everything afresh and the problem still exists. 

This is on Debian 11 amd64 with jdk 1.8.0_321 and jai-1_1_3

Could someone test the sdf file I'm attaching (inside the zip) to see if it works for you?
[pk.zip](https://github.com/Starlink/starjava/files/8170701/pk.zip)

Many thanks
Paul

**Comment by pwdraper** [comment]
I've cherry picked the rebuilt libraries from 2021A to master. So pull and rebuild.

BTW, this file opened with the 2021A vanilla release. Are you using that?

**Comment by paulkerry1** [comment]
Thanks both.
I've pulled and rebuilt starjava and everything works perfectly.
Peter - no is the short answer: we have to do a starlink source build as we have need of other software that won't build on Debian unless that is the case, so then I build starjava as well. I last rebuilt starlink and starjava on 2021.09.24 so will have to do so again as I notice 2021A was released 2021-12-27
Regards
Paul.

**Comment by mmpcn** [comment]
Hi

Still doesn’t work for me. It seems the native libraries were updated only for amd64.
Does not work on a MacBook with x86_64 for example.

Best regards,

Margarida

**Comment by dsberry** [comment]
That's probably because as yet there is no 2021A Starlink for MacOS. We hit a problem on MacOS caused by gfortran changing to use 8-byte integers to represent string lengths passed as hidden arguments on the end of each Fortran subrfoutine call. This change applies to Linux too, but on Linux the change is benign whereas on MacOS is causes seg faults. We think we have solved this problem and are currently in the process of generating new builds, including a MacOS build.
