### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by olebole** [Starlink/starjava#9]
Hi,

it is quite difficult to find out the licensing information of Starjava. Would it be possible to put a `COPYRIGHT` file into each component with the appropriate ((L)GPL?) license? This would help to document the license when creating packages for the components.

**Comment by mbtaylor** [comment]
Following some discussion with @olebole, I've prepared a short top-level LICENSE.txt file and made one or two other changes on branch `license`.  This claims the LGPL for all original (not third-party) code in the repository.  This apparently is good enough for Ole.

Since I find it very hard to get interested in licensing issues, I'd appreciate it if other interested parties could take a look and say whether they think it looks OK - @pwdraper, @timj, @mmpcn?

**Comment by timj** [comment]
My reading of the historical documents relating to the licensing of Starlink code, is that there was a clear intent for libraries to be LGPL and applications to be GPL (SLALIB was an exception to this rule and must be GPL). That does make it a bit tricky when you have some application code that you want to refactor into an existing LGPL library but I try not to think about that. There is no point asking RAL for clarification unless there has been a shift in UK government policy on licensing that we wish to take advantage of.

**Comment by mbtaylor** [comment]
The applications (TOPCAT and STILTS at least) are GPL whether we like it or not, because they use some libraries that are themselves GPL.  I haven't mentioned that fact in the license file, though I could add some explicit comment to that effect.  The assertions I've made are about the non-third party source code, including the `uk.ac.starlink.*` classes that are used within the applications.  In fact if there are parts of the applications that you want to use outside of those applications (people do make use in third-party applications of parts of the TTOOLS package within which STILTS lives), then those classes are in that context library code.

So, in my (not particularly expert) opinion, I don't think the sky or RAL will fall on our heads if we assert the LGPL in this way.

In view of that point, unless you say different, I won't interpret your comment to mean that you consider a change required to the draft license text as it stands.

**Comment by timj** [comment]
I didn't read any of your text but it sounds fine (I was too lazy to look and there wasn't a pull request referenced here to make it easy) 😉

**Comment by pwdraper** [comment]
I'm happy with this change. It is true as far as I know that starlink tree is unencumbered, and as you say all this code is potentially extensible, so why not realised under the LGPL.

**Comment by mbtaylor** [comment]
Thanks chaps.  Branch merged at 8f416cd.  I believe this is ready to close.

**Comment by olebole** [comment]
Looks fine for me! I will update the licensing information in the packages accordingly. 1000 thanks! This really helps very much!
